name: cd

on:
    push:
        branches: [main]

jobs:
    Deploy:
        name: Deploy
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v4            
            
            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                go-version: "1.22.0"

            - name: Verify Go installation
              run: go version

            - name: Make script executable
              run: chmod +x ./scripts/buildprod.sh

            - name: Build
              run: ./scripts/buildprod.sh
